<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Agenda 2030	</title>

	
	<link href="/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">


	<link href="/assets/css/freelancer.min.css" rel="stylesheet">
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	
	<script src="http://www.geradorcpf.com/scripts.js"></script>

	<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<script type="text/javascript">	
	
	
		

	</script>		

</head>

</head>

<body id="page-top"> 

  
  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="home"><img src="/assets/img/logo_plataforma.png" alt=""  style= height:100px	;"></a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mx-0 mx-lg-1">
		    <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="home">Home</a>
          </li>
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Conheça</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">Sobre</a>
          </li>
		   <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="form">Nossa Pesquisa</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

 
  <header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">

     
      <img class="masthead-avatar mb-5" src="/assets/img/portfolio/safe.png" alt="" style= width:500px height:500px;>


    </div>
  </header>


  <section class="page-section portfolio" id="portfolio">
    <div class="container">

     
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Conheça</h2>

     <br>

   
      <div class="row">
        <div class="col-lg-4 ml-auto">
          <p class="lead">O mundo é mais desigual hoje do que em qualquer momento da história desde 1940. A desigualdade de renda e na distribuição da riqueza dentro dos países têm disparado, incapacitando os esforços de alcance dos resultados do desenvolvimento e de expansão das oportunidades e habilidades das pessoas, especialmente dos mais vulneráveis. A desigualdade é um problema global que requer soluções integradas. A visão estratégica deste objetivo se constrói sob o objetivo da erradicação da pobreza em todas suas dimensões, na redução das desigualdades socioeconômicas e no combate às discriminações de todos os tipos.</p>
        </div>
        <div class="col-lg-4 mr-auto">
          <p class="lead">Seu alcance depende de todos os setores na busca pela promoção de oportunidades para as pessoas mais excluídas no caminho do desenvolvimento. Foco importante do ODS 10 é o desafio contemporâneo das migrações e fluxos de pessoas deslocadas entre países e regiões devido a conflitos, eventos climáticos extremos ou perseguições de quaisquer tipo. O alcance de suas metas é estruturante para a realização de todos os outros 16 Objetivos de Desenvolvimento Sustentável.</p>
        </div>
      </div>
    

 
  </section>
<br>
<br>
 
  <section class="page-section bg-primary text-white mb-0" id="about">
    <div class="container">

      
      <h2 class="page-section-heading text-center text-uppercase text-white">Sobre</h2>

     <br>

       <div class="container d-flex align-items-center flex-column">

      
      <img class="masthead-avatar mb-5" src="/assets/tabela2.png" alt="" >

<img class="masthead-avatar mb-5" src="https://agenciadenoticias.ibge.gov.br/images/agenciadenoticias/estatisticas_sociais/2018_12/SIS-Pobreza1488.png" alt="" style= width:700px height:700px;>


       <div class="text-center mt-4">
        <a href="http://www.agenda2030.org.br/ods/10/" target="_blank" ><button class="btn btn-primary">
                  </i>
                  Participe
                </button>
				</a>
      </div>
    </div>
    </div>
  </section>
  


  <section class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Orgulhosamente desenvolvido por Murilo Godói e Guilherme Isler</small>
    </div>
  </section>

  
  <div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>

  

 


  <script src="/assets/vendor/jquery/jquery.min.js"></script>
  <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  <script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

 
  <script src="/assets/js/jqBootstrapValidation.js"></script>
  <script src="/assets/js/contact_me.js"></script>

 
  <script src="/assets/js/freelancer.min.js"></script>

</body>

</html>
