<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Agenda 2030	</title>

  
  <link href="/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

 
  <link href="/assets/css/freelancer.min.css" rel="stylesheet">

</head>

<body id="page-top"> 


  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="home"><img src="/assets/img/logo_plataforma.png" alt=""  style= height:100px	;"></a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mx-0 mx-lg-1">
		    <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="home">Home</a>
          </li>
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Conheça</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">Sobre</a>
          </li>
		   <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="form">Nossa Pesquisa</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

 
  <header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">

     
      <img class="masthead-avatar mb-5" src="/assets/img/portfolio/game.png" alt="" style= width:500px height:500px;>


    </div>
  </header>


  <section class="page-section portfolio" id="portfolio">
    <div class="container">

      
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Conheça</h2>

     <br>

     
      <div class="row">
        <div class="col-lg-4 ml-auto">
          <p class="lead">De acordo com a pesquisa realizada pela UNICEF em julho de 2017, cerca de 2,1 bilhões de pessoas não tem acesso a água potável em casa, e mais do dobro de pessoas não tem acesso a saneamento seguro. Valor representa 3 em cada 10 pessoas em todo o mundo, representando uma quantidade catastrófica.</p>
        </div>
        <div class="col-lg-4 mr-auto">
          <p class="lead">A falta de água pode causar cansaço, cãibras, constipação e até mesmo a morte. A falta de saneamento traz inúmeras doenças, como: Leptospirose, Disenteria Bacteriana, Esquistossomose, Febre Tifóide e Cólera. Sendo assim, esse item da agenda é extremamente importante e urgente.</p>
        </div>
      </div>
      

 
  </section>
<br>
<br>
  
  <section class="page-section bg-primary text-white mb-0" id="about">
    <div class="container">

  
      <h2 class="page-section-heading text-center text-uppercase text-white">Sobre</h2>

     <br>

       <div class="container d-flex align-items-center flex-column">

      
      <img class="masthead-avatar mb-5" src="/assets/tabela.png" alt="" >

		<img class="masthead-avatar mb-5" src="https://lh4.googleusercontent.com/2Yi2Jf5_8enaZFlzzf0mNbd1h0LEfZMNzF6dfKaPc27aA6FHWNS-dDAZmdV5NicEmfmWsYjPDZgen3rVss0D8Lg5PNosXnSnJ5zw1A0MZlrJ5jtL1YEjTgQvmGsgc9Kmg_2_XMoV" alt="" style= width:800px height:800px;  >


       <div class="text-center mt-4">
        <a href="http://www.agenda2030.org.br/ods/6/" target="_blank" ><button class="btn btn-primary">
                  </i>
                  Participe
                </button>
				</a>
      </div>
    </div>
    </div>
  </section>



  


  <section class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Orgulhosamente desenvolvido por Murilo Godói e Guilherme Isler</small>
    </div>
  </section>

  
  <div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>

  

 

  
  <script src="/assets/vendor/jquery/jquery.min.js"></script>
  <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

 
  <script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

  
  <script src="/assets/js/jqBootstrapValidation.js"></script>
  <script src="/assets/js/contact_me.js"></script>

 
  <script src="/assets/js/freelancer.min.js"></script>

</body>

</html>
